### ISSUE TITLE
not a debian format archive

### ISSUE THREAD

**Issue by toddjcrane** [onfsdn/atrium-docs#1]
I can't seem to install the OFDPA package.

I've tried with the binary version of ONL and one I compiled myself, to no avail. Then after debugging dpkg, I found this error. 

dpkg-deb: error: `ofdpa-i.12.1.1_12.1.1+accton1.7-1_amd64.deb' is not a debian format archive

dpkg -i --force-overwrite -D113 ofdpa-i.12.1.1_12.1.1+accton1.7
D000010: ensure_pathname_nonexisting '/var/lib/dpkg/tmp.ci'
dpkg-deb: error: `ofdpa-i.12.1.1_12.1.1+accton1.7-1_amd64.deb' is not a debian format archive
dpkg: error processing ofdpa-i.12.1.1_12.1.1+accton1.7-1_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
D000010: ensure_pathname_nonexisting '/var/lib/dpkg/tmp.ci'
D000010: ensure_pathname_nonexisting '/var/lib/dpkg/reassemble.deb'
Errors were encountered while processing:
 ofdpa-i.12.1.1_12.1.1+accton1.7-1_amd64.deb

Note: the instructions I'm following... https://wiki.onosproject.org/display/ONOS/Hardware+Switch+Installation+Guide

**Comment by toddjcrane** [comment]
User error

**Comment by sauravdas2** [comment]
Todd the issue is not with the debian packages for OF-DPA. The problem is that the debian packages no longer work with the lastest ONL installers. 
I have updated the wiki pages both here:
https://wiki.onosproject.org/display/ONOS/Hardware+Switch+Installation+Guide
and here:
https://github.com/onfsdn/atrium-docs/wiki/Hardware-Install-ONOS-Fabric-16A

to reflect the ONL installer to use with the provided debian packages for OF-DPA
